### ISSUE TITLE
Error in Meteor production mode

### ISSUE THREAD

**Issue by tehXor** [loneleeandroo/ngMeteor#15]
Hi there,

when I try to run my app (which works flawlessly in the "normal" non productive mode) with "meteor run --production" none of my templates get rendered. So I just see the frame of the main HTML file and nothing from within the ng-view directive. And I get the following AngularJS error (this why I suspect that ngMeteor is the culprit for the problem):
Uncaught Error: [$injector:unpr] Unknown provider: eProvider <- e
( http://errors.angularjs.org/1.2.11/$injector/unpr?p0=eProvider%20%3C-%20e )

Can someone confirm before I start troubleshooting (which could get ugly as production mode is not meant for troubleshooting and everything is in this one uglified JavaScript file...) that ngMeteor should work or not work in production mode? And even if it normally should work in production, where would be a good place to start looking into this problem?

Thanks for any tips!

**Comment by loneleeandroo** [comment]
Hello :)

When you use the production option all the javascript code gets minified and obfuscated, which means that all the variables are renamed, so you need to make sure that all your controllers and directives use dependency injection. Look at [this](https://github.com/loneleeandroo/ngMeteor#adding-controllers-directives-filters-and-services) in the README and read this [article](http://docs.angularjs.org/guide/di) in the AngularJS guide.

So instead instead of doing this:

```
ngMeteor.controller('TodoCtrl', function($scope, $collection) { ... });
```

you need to do this:

```
ngMeteor.controller('TodoCtrl', ['$scope', '$collection', 
    function($scope, $collection) { ... }
]);
```

If you've done that already :) copy and paste the code here so I can have a look.

**Comment by tehXor** [comment]
Thanks for the super fast and helpful reply! I used DI everywhere correctly expect in one modules .run function (no idea why...). I guess I would have needed ages to figure that out on my own... But now my app works as expected :) 
Thanks again for your help and also for the great work with ngMeteor!!
